apiVersion: "v1"
kind: Pod
metadata:
  name: transcribe
  labels:
    name: transcribe
    app: voicemail
spec:
  containers:
    - name: transcribe
      image: mycluster.icp:8500/voicemail/transcribe:0.1
      env:
        - name: RABBIT_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq
              key: rabbitmq-password
        - name: SPEECH_TO_TEXT
          valueFrom:
            secretKeyRef:
              name: speech-to-text
              key: binding
