apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: voicemailstore
  labels:
    name: voicemailstore
    app: voicemailstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voicemailstore
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: voicemailstore
    spec:
      containers:
        - name: voicemailstore
          image: mycluster.icp:8500/voicemail/voicemailstore:0.1
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          env:
            - name: OBJECT_STORAGE
              valueFrom:
                secretKeyRef:
                  name: object-storage
                  key: binding
