kind: Service
apiVersion: v1
metadata:
  name: voicemailstore
spec:
  selector:
    app: voicemailstore
  #type: ClusterIP
  type: NodePort
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
